// <auto-generated />
namespace MS.Gamification.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GA20ObservingLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GA20ObservingLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201604220026296_GA20-ObservingLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
